State:6
Info:正式版 1.20.1, Forge 47.4.10, Authlib 验证
Logo:pack://application:,,,/images/Blocks/CobbleStone.png
ReleaseTime:2023-06-12 21:25
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:47.4.10
VersionNeoForge:
VersionVanillaName:1.20.1
VersionVanilla:20.0.1
VersionArgumentIndieV2:True
LogoCustom:True
VersionServerAuthServer:https://littleskin.cn/api/yggdrasil
VersionServerLogin:4
VersionServerAuthRegister:https://littleskin.cn/auth/register
VersionServerAuthName:LittleSkin 登录
