#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Mar 17 21:44:32 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=SEUS-Renewed-v1.0.1.zip
enableShaders=false
